# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classchedules', '0001_initial'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='class_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classchedules.ClassSchedule'),
        ),
    ]
