# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.CharField(max_length=30)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
            ],
        ),
    ]
