# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 07:08
from __future__ import unicode_literals

import bulletins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=bulletins.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
