# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
