# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classchedules', '0001_initial'),
        ('schedules', '0002_remove_schedule_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='class_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classchedules.ClassSchedule'),
        ),
    ]
