# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
